### ISSUE TITLE
[BREAKING CHANGE]: Profile page vs. Twtxt feed URL?

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#15]
I'm _thinking_ of potentially changing a key important critical feature of `twtxt` and on the hosted instance https://twtxt.net/ that would break existing feeds there and anyone else that has since spun up their own instance.

Basically I'm _thining_ about this:

> Should https://twtxt.net/u/prologic by a "sort of" Profile page for me?
> (_There is no Personal Identifiable Information / PII that `twtxt` stores at this time but it _might_ be a useful feature one day?_)

If we decide to do this I would change the Twtxt feed URIs to match those of [rss2twtxt](https://github.com/prologic/rss2twtxt) over at https://feeds.twtxt.net/feeds

Now is the time to do it while the usage and no. of `twtxt` is low. Comments?

**Comment by lwojcik** [comment]
HI, [lukem](https://twtxt.net/u/lukem) here. I'm exercising the idea of spinning my own twtxt instance and this issue is something I want to follow.

As a user, 'mainstream' social media (Twitter etc.) taught me to expect that whenever I click on user's nickname I get a profile page that lets me easily scan this user's latest activity. Obviously it's still perfectly possible with raw Markdown files but it's not the nicest experience and it breaks my immersion. :)

I don't have strong opinions on the technical aspect of this change but I agree it's a good time to do it now rather than later.

**Comment by prologic** [comment]
Cool! I'm glad you agree! I will be implementing this tomorrow!

What I'm really quite pleased with though (_aside from the uptake WOW!_) is that you are willing to spin up your own instance. That will be so amazing ! 🎉 I built this thing for two reasons:

- To make getting into the twtxt community easier for _anyone_.
- To encourage more folks like yourself to spin up their own either private single-user instance or a small family/community instance.

So Thank you! I'll post on this issue when I've made all the changes. It will be a PR for review.

**Comment by prologic** [comment]
Done. Please help me review and test the PR :)

**Comment by lwojcik** [comment]
That might take some time as I have zero experience with Go ecosystem and I still have to set up my own twtxt instance, but I'll try to arrange some time to do so and check this PR out either this or next week. Stand by.

**Comment by prologic** [comment]
Let me know if ou need any help at all? There is also a 1Dockerfile` so you can get going quickly that way too.

**Comment by prologic** [comment]
@lwojcik Any change to test these changes in the linked PR yet?

**Comment by prologic** [comment]
I am _thinking_ however of adding an additional final commit here around these lines:

https://github.com/prologic/twtxt/blob/bca429abbefcbc8aec727fc219578121e7a09d09/server.go#L197-L199

And a redirect for old URIs.

My _thinking_ here is if I change the URIs completely to something with a different prefix path entirely say `twtxt.net/user/prologic` and `twtxt.net/user/prologic/twtxt.txt` I can more easily setup redirects on the old `twtxt.net/u/<user>` URIs so existing clients already following (_and there are quite a few already_) [twtxt.net](https://twtxt.net) users don't break or end up with bad data.

**Comment by lwojcik** [comment]
Yup, I ran the instance with the changes from the PR branch, LGTM. Much better to see that page instead of a raw feed.

**Comment by prologic** [comment]
Cool. I'll probably do the new URI scheme then and put redirects in place before merging and launching a new version with this PR.

I know there are a few UI/UX issues with it (_but I'm no CSS expert so I'll have to seek out help for that_) like:

- Unfriendly mobile topnav
- The icons don't quite line up properly

But this is "good enough"™  to go with and iterate on :)

**Comment by prologic** [comment]
Okay this is ready to merge and deploy now! 🤞
