### ISSUE TITLE
[UI/UX]: Margins between posts  are large and waste screen real estate on desktop

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#28]
See https://github.com/picocss/pico/issues/2

**Comment by lucaslarroche** [comment]
As it's a [deliberate choice](https://github.com/picocss/pico/issues/2#issuecomment-663329462) in pico, you have 2 solutions :

1. You can disable all responsive spacings in the [config file](https://github.com/picocss/pico/blob/master/scss/_variables.scss) ([line 16](https://github.com/picocss/pico/blob/master/scss/_variables.scss#L16)).

2. You can personalize pico for twtxt if you want to disable responsive spacings only for [cards](https://picocss.com/docs/#cards) `<article>`.

[Please find attached an example](https://github.com/prologic/twtxt/files/4970067/twtxt_customcss.zip) to integrate and personalize pico. 
In this example I have deleted the responsive margins on Cards `<article>`.

**Comment by prologic** [comment]
@lucaslarroche Thank  you :) Ill have a play with this over the weekend. Much appreciated! 🙇‍♂️
