### ISSUE TITLE
How do I enable registration on a localhost instance?

### ISSUE THREAD

**Issue by lwojcik** [prologic/twtxt#29]
Hi!

I followed installation steps detailed in the readme and managed to get twtxt up and running locally on my Ubuntu 20.04 workstation. However, I can't figure out how to enable registration process so that I could post some test content.

Am I missing something obvious here?

**Comment by flavienbwk** [comment]
Same problem. I don't understand why registration is disabled!

**Comment by prologic** [comment]
You just add the `-r` flag to the `twtd` startup.

Example:

```#!sh
twtd -r
```

**Comment by prologic** [comment]
Registrations are just disabled by default. The _idea_ was to be a closed beta at first -- But that required a lot more effort so it didn't happen so when I launched [twtxt.net](https://twtxt.net) I just opened it up to all! But the feature remains to encourage operators of instances to control whether they want open registrations or not. Improves features here would include a CLI or UI for administering the instance, adding accounts manually, etc and putting a cap on registrations.

Anyway I'll put up a PR to fix this issue now by documenting this in the [README](/README.md) and logging a warning on startup.

**Comment by prologic** [comment]
Done. Will be committed and pushed shortly:

```#!sh
$ make
INFO[0000] Calibrating scrypt parameters ...
INFO[0001] scrypt params                                 params="{32768 8 5 16 32}"
INFO[0001] started background jobs
INFO[0001] Instance Name: twtxt.net
INFO[0001] Base URL: http://0.0.0.0:8000
INFO[0001] User Registrationg: true
INFO[0001] Max Tweets per Page: 50
INFO[0001] Maximum length of Posts: 288
INFO[0001] twtd listening on http://0.0.0.0:8000
```

Without `-r/--register`:

```#!sh
$ ./twtd
INFO[0000] Calibrating scrypt parameters ...
INFO[0002] scrypt params                                 params="{32768 8 5 16 32}"
INFO[0002] started background jobs
INFO[0002] Instance Name: twtxt.net
INFO[0002] Base URL: http://0.0.0.0:8000
INFO[0002] User Registrationg: false
INFO[0002] Max Tweets per Page: 50
INFO[0002] Maximum length of Posts: 288
WARN[0002] User registrations are disabled as per configuration (no -r/--register)
INFO[0002] twtd listening on http://0.0.0.0:8000
```
