### ISSUE TITLE
[usability] register form on dark mode

### ISSUE THREAD

**Issue by marado** [prologic/twtxt#3]
Hi!

On dark mode, typing on the register form fields will be showing the user black text on dark background, which is very hard to read.
The color of the text on the fields you are not actively typing on, however, is perfectly fine for dark mode.

**Comment by prologic** [comment]
Hmmm 🤔 this is all using [PicoCSS](https://picocss.com) which I'm starting to _slightly_ regret. Yes its damn simple to use, but perhaps a little too simple? I'm thinking of going back and redoing the UI/UX with my favourite (_which a lot of my other [Self-hosted Apps](https://gist.github.com/prologic/c165403fb6ac07c16dc9fd6eeb8efbd2) use_) [SpectureCSS](https://picturepan2.github.io/spectre/).

I'm not a UI/UX / CSS designer though (_can you tell?!_); so I'm open to ideas/suggestions here that don't involve me wrangling with CSS for hours :)

**Comment by prologic** [comment]
Hmm 🤔 I can't actually reproduce this. What browser/environment did you see this in?

See screenshot (I'm on macOS with Chrome).
<img width="1312" alt="Screen Shot 2020-07-20 at 11 32 21" src="https://user-images.githubusercontent.com/1290234/87891275-c2223a80-ca7c-11ea-8329-b28742858095.png">

**Comment by prologic** [comment]
Never-mind. Installed Firefox and repro'd there. Thanks! I'll get this fixed ASAP, that's a bit of a bug bear :)

**Comment by prologic** [comment]
@lucaslarroche Are you able to help with this since I'm using your [PicoCSS](https://picocss.com)? Thanks!

**Comment by dacz** [comment]
I believe this is it:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/46513/87965181-a25e3700-cabb-11ea-92b9-5498c695c2c3.png">
`color: transparent`

**Comment by prologic** [comment]
@lucaslarroche ☝️ Any ideas why you did this? Can you fix it in PicoCSS and release a new version?

**Comment by lucaslarroche** [comment]
I reproduced the bug as well.
`:moz-focusring` is a non-standard feature and not useful anymore.
It was a bad practice to remove this helper outline on Firefox.

As a quick fix, you can simply delete this part of code :

```CSS
input:focus:-moz-focusring,
select:focus:-moz-focusring,
textarea:focus:-moz-focusring {
  color: transparent;
  text-shadow: 0 0 0 #000;
}
```

I will perform more tests and release a new version of Pico.

**Comment by prologic** [comment]
> I will perform more tests and release a new version of Pico.

Thank you! We can wait for the fix. This help be of great benefit to our Firefox users :) 🙇‍♂️

**Comment by lucaslarroche** [comment]
Fix is here : https://github.com/picocss/pico/releases/tag/v1.0.3

**Comment by prologic** [comment]
Fixed confirmed! Thank you!

<img width="1392" alt="Screen Shot 2020-07-21 at 13 03 48" src="https://user-images.githubusercontent.com/1290234/88008032-a721fa00-cb52-11ea-8e4e-fa38f3032d8b.png">
