### ISSUE TITLE
[Installation] Cannot build or run

### ISSUE THREAD

**Issue by kseistrup** [prologic/twtxt#30]
The following applies to 08fcf9aa0bc9e221ccf1690207ee05001e4dccbb:

Running

```sh
$ go get -u github.com/prologic/twtxt/...
```

goes well and provides me with an unstripped binary named `twtd`. Sweet.

However,

```sh
$ twtd -r
time="2020-07-25T05:58:45Z" level=error msg="error finding templates" error="could not locate box \"templates\""
time="2020-07-25T05:58:45Z" level=error msg="error loading templates" error="could not locate box \"templates\""
time="2020-07-25T05:58:45Z" level=fatal msg="error creating server" error="could not locate box \"templates\""
```

Box? What box?

Ok, so since the git repo has a `templates` directory, perhaps that's what it wants:

```sh
$ git clone https://github.com/prologic/twtxt.git && cd twtxt
$ twtd -r
time="2020-07-25T06:00:56Z" level=error msg="error finding templates" error="could not locate box \"templates\""
time="2020-07-25T06:00:56Z" level=error msg="error loading templates" error="could not locate box \"templates\""
time="2020-07-25T06:00:56Z" level=fatal msg="error creating server" error="could not locate box \"templates\""
```

No luck. Well, let's try the sources.

```sh
$ https://github.com/prologic/twtxt/archive/0.0.7.tar.gz
$ tar xf 0.0.7.tar.gz && cd twtxt-0.0.7
$ make build
make: rice: No such file or directory
make: *** [Makefile:21: generate] Error 127
```

Hm…, what is `rice`?

I feel I'm missing something essential.

----

```sh
$ uname -a  # ArchLinux
Linux ymerdrys 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
$ go version
go version go1.14.6 linux/amd64
```

**Comment by skx** [comment]
`rice` is a utility to allow embedding files, etc.  You can find it here:

* https://github.com/GeertJohan/go.rice

(I have no knowledge of txtxt, saw this bug randomly.)

**Comment by prologic** [comment]
@skx Is right. What's happening here is what happens a lot with projects that need resources like static assets and templates. Typically with other projects of mine I would have published binaries by now with everything embedded in them ready to rock 'n roll. In this case I haven't done so yet.

If you run:

```#!sh
$ make deps
$ make
```

From a Git clone you'll end up with a working version.

I'm not sure how else to make this better right now. The `docker build` should also work correctly as that also ensures the `rice` tool is installed beforehand. Open to ideas though that don't horribly break the existing codebase or existing production environment at https://twtxt.net/ :)

**Comment by kseistrup** [comment]
@prologic, that's fine, `make deps && make build` was all that was needed — thanks!

**Comment by prologic** [comment]
I guess we should update/fix the [README](/README.md) as the "instructions" are really kind of wrong, as this project is not _strictly_ speaking `go get`'able. Right?

**Comment by prologic** [comment]
We _might_ spin off some of the code over the coming weeks into separate Go libraries that can be maintained and reused separately -- But that's a separate topic/issue.

**Comment by kseistrup** [comment]
> this project is not _strictly_ speaking `go get`'able. Right?

Correct. I did get a `twtd` binary, only it didn't work. Better tell people to clone the repo and do the make dance.

**Comment by prologic** [comment]
Okay I'll update the README.
