### ISSUE TITLE
Are config.go params replaced when set as environment variables ?

### ISSUE THREAD

**Issue by flavienbwk** [prologic/twtxt#31]
Hi,

For an easier use of this project with docker-compose, I would like to know if the variables set in `config.go` are automatically replaced when set as environment variables.

I see in the swarm config (`twtxt.yaml`) that you set the `COOKIE_SECRET` env variable but apart from `config.go` line `20` I don't see this variable anywhere.

Thank you.

**Comment by prologic** [comment]
This is handled by the following code:

https://github.com/prologic/twtxt/blob/08fcf9aa0bc9e221ccf1690207ee05001e4dccbb/cmd/twtd/main.go#L52-L75

So yes.
