### ISSUE TITLE
Docker swarm documentation typo? 

### ISSUE THREAD

**Issue by flavienbwk** [prologic/twtxt#34]
Hi,

Currently, the documentation is stating that you have to run the following command if you want to start your swarm configuration :

```
docker stack deploy -c twtxt.yml
```

But the file present at the root of the project is a `.yaml`. Is this an error?

Moreover, what about changing the extension from `yaml` to `yml` (more widely used) so both the Docker compose and swarm config files are using the same extension?

**Comment by prologic** [comment]
That was a typo :) My Docker Swarm production cluster have many years of tooling I built. Sorry!

**Comment by prologic** [comment]
Fixed :)
