### ISSUE TITLE
Including followers in User-Agent header

### ISSUE THREAD

**Issue by hjertnes** [prologic/twtxt#35]
Most of the other twtxt clients let users opt into sharing who they are in the User-Agent header when they fetch a twtxt file.

This is great because almost anything can read it from a web server log or through some simple back end system. 

It would be great if twtxt.net had a way for us non twtxt.net users could see followers on twtxt.net.

I get that the feeds probably isn't fetched once per user who follows it on a web based system. But this could be solved by including all followers in the header on fetching or by adding a url where the information is available

**Comment by prologic** [comment]
> I get that the feeds probably isn't fetched once per user who follows it on a web based system. But this could be solved by including all followers in the header on fetching or by adding a url where the information is available

I'm open to adding a custom header to go along with or something. Q: (_remind me_) how long can headers be again? :) 

In fact this probably makes the most sense actually, from a privacy perspective users can still choose to opt in on whether they want to surface that they follow a feed or not.

What do you think?

**Comment by hjertnes** [comment]
I think opt-in is the way to go, but encouraging users to do it, because of how important it is for discovery and community growth. 

HTTP Headers doesn't have a limit in the standard, but web servers might have. 

I personally would prefer it if you included a URL in the header instead of listing a bunch of users there. The web page should either be html or json (or both?), with a list of handles and url's to their twtxt's. And it should also be easy to access without a twtxt.net user.

**Comment by prologic** [comment]
I'm a bit confused by your last statement; Do we want a list of follower URIs in the Headers or a JSON/HTML view or both?

**Comment by hjertnes** [comment]
Sorry about that. 

I just meant I'd be fine with either. Maybe a HTML version in the header, plus some API endpoint that returns JSON in addition?

**Comment by dooven** [comment]
Will adding a new route, say `https://twtxt.net/u/<user>/followers`, makes sense? Then we can add `https://twtxt.net/u/<user>/followers?json=true` if we want to display it in JSON format

**Comment by hjertnes** [comment]
Maybe using the Accept header instead of the query param?

**Comment by dooven** [comment]
Yeah that makes more sense. May I work on this one?

**Comment by dooven** [comment]
Hi :wave:  I created this [branch](https://github.com/prologic/twtxt/compare/master...dooven:add-followers-page) that adds: 
- User can choose to set to show their followers publicly
- If you go to `https://twtxt.net/user/<nickname>/followers`, it'll show the user's followers. If you change the Accept header to application/json, it'll show it as a JSON format
Lmk if it covers the scope for this issue & i'll put up a PR :sweat_smile:

**Comment by prologic** [comment]
> Will adding a new route, say `https://twtxt.net/u/<user>/followers`, makes sense? Which will display it in HTML version by default
> 
> Then we can add `https://twtxt.net/u/<user>/followers?json=true` if we want to display it in JSON format

Yes! This would work. Bare in mind through that #15 and [v0.9.0](https://github.com/prologic/twtxt/releases/tag/0.0.9) broke this URL structure `/u/` in favor of two separate ones `/user/` for a user's profile and `/user/twtxt.txt` for the user's actual twtxt feed.

But yes same idea can be applied!

**Comment by prologic** [comment]
> Yeah that makes more sense. May I work on this one?

Please! I welcome any contributor! 🎉

**Comment by prologic** [comment]
> Hi 👋 I created this [branch](https://github.com/prologic/twtxt/compare/master...dooven:add-followers-page) that adds:
> 
> * User can choose to set to show their followers publicly
> * If you go to `https://twtxt.net/user/<nickname>/followers`, it'll show the user's followers. If you change the Accept header to application/json, it'll show it as a JSON format
>   Lmk if it covers the scope for this issue & i'll put up a PR 😅

Oh WOW! This  is fantastic! Please submit a PR :) I'll happily review it!

**Comment by hjertnes** [comment]
Is it <nickname> or <twtxt-file-url>?

**Comment by prologic** [comment]
> Is it nickname or twtxt-file-url?

It should just be URLs I think.  "Nickname" are a personal user thing.

**Comment by dooven** [comment]
I've put up a PR here #45 

> > Is it nickname or twtxt-file-url?
> 
> It should just be URLs I think. "Nickname" are a personal user thing.

Sorry i just notice this comment above. Right now im just using the username `/user/<username>/followers`. What should be the URL look like? :sweat_smile: Im a bit confused

**Comment by prologic** [comment]
I think the way you've done it is fine :) We were the ones confused!
