### ISSUE TITLE
"Follow" vs. "Unfollow"

### ISSUE THREAD

**Issue by marado** [prologic/twtxt#4]
Hi there!

https://twtxt.net/discover shows a "follow" button in front of everyone, even those you already follow. It would be way better if it, for those you already follow, an "Unfollow" button would be presented instead.

**Comment by prologic** [comment]
Yeah I agree. I _thought_ of this as well, shouldn't be too hard to do, the `Context`'s `.User` object is already there.

You willing to put up a PR for this?

**Comment by marado** [comment]
Sorry, I don't know if I will find the time for it.

**Comment by prologic** [comment]
That's okay :) I'll have this done today hopefully. Thanks for your submissions/issues so far!
