### ISSUE TITLE
Feature request: Allow linking to individual posts

### ISSUE THREAD

**Issue by dbohdan** [prologic/twtxt#42]
It would be nice to give every post an id you can link to.  It could be the timestamp (https://twtxt.net/user/example#2020-07-27T12:28:43Z).

**Comment by lwojcik** [comment]
It's being discussed in #32 and it will probably happen.

**Comment by prologic** [comment]
Yeah in general this would be nice, and I'm glad you've brought it up! Your _specific_ example won't work though as that uses a client-side ref on the page or that has to be interpreted by some JS to do some "magic".

What I was thinking of was the following:

- Each post that is either fetched from external feeds/users or local users is hashed.
- We use the hash as a reference for that post and link to it.

Now the [twtxt](https://twtxt.readthedocs.org) spec says nothing about the immutability of twtxt feeds or their order. So if when fetching feeds we find that the content of a post has now changed, we just hash the new content, store that and preserve the old hash.

This has a side effect of on twtxt.net instance posts and their original content are preserved.

What do you think? I was also thinking of using specifically a FNV hash.

**Comment by dbohdan** [comment]
If you want to prevent users from changing a post someone has linked to (which *is* a potential source of bait-and-switch trolling), I think hashing the post + the timestamp and using the hash as the fragment identifier is a good way to do it.

Why a FNV hash?  Since this is a kind of [content addressing](https://en.wikipedia.org/wiki/Content-addressable_storage), you should default to a cryptographic hash function.

**Comment by prologic** [comment]
> Why a FNV hash? Since this is a kind of content addressing, you should default to a cryptographic hash function.

Hmmm actually you are right. I was thinking about something else (_which I'll talk about in another issue_).

Did you want to try to implement this btw? I'm of course open to PRs and new contributors :)
(_can't do everything myself!_)

**Comment by dbohdan** [comment]
@prologic I've made a PR.  Please review.

**Comment by prologic** [comment]
> @prologic I've made a PR. Please review.

Oh 😲 Thank you very much! I will review shortly and probably merge and redeploy along with #40
