### ISSUE TITLE
Followers link doesn't work for Feeds

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#52]
Steps to reproduce:

- Click on a feed's profile; e.g: https://twtxt.net/user/stats
- Click on "Followers"

Observe the "User not found" error.

**Comment by dooven** [comment]
Same thing happens with https://twtxt.net/user/twtxt

**Comment by prologic** [comment]
@shahxeb Can you fix this this week? Thanks 👍

**Comment by dooven** [comment]
I can put up a PR this one. I think I know where it's broken
