### ISSUE TITLE
Investigate whether "Followers" for Feeds are being updated

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#54]
@dooven I _think_ this _might_ be another related bug or missing feature I overlooked.

There is a `Feed` entity as you know by now with its own "Followers" list; but I think it isn't getting updated for some reason. Needs to be confirmed/reproduced in a local instance.

Did you want to take this on? If it turns out to be a bug like I suspect a migration function for the `FixUserAccountsJob` will also have to be written to fix the missing data by processing all users "Following" entries and fixing the missing data.

Up for it? :)

**Comment by dooven** [comment]
For sure. I'll take a look at this one later :eyes:

**Comment by dooven** [comment]
I have a PR for it #62 The follower handler needs to use `GetFeed` when user tries to follow a feed & call `SetFeed` when setting the followers for that feed.

**Comment by prologic** [comment]
@dooven Brilliant!

Only one thing you forgot to do, write a "migrate" function in `FixAccountsJob` to fix the _now_ bad data on [twtxt.net](https://twtxt.net) and possibly any other instances out there in the wild (_none that I know of just yet but @lwojcik is planning on spinning one up soon!_)

**Comment by prologic** [comment]
This has been deployed to production 🎉

**Comment by dooven** [comment]
Oops. totally forgot about that Just wondering if we can re-open this issue. :sweat_smile: I'll take a look at adding the migration

**Comment by prologic** [comment]
I did it in ebf388fc81ddbb1143be98963784db6a76493ede

**Comment by prologic** [comment]
And redeployed! Hopefully the bad data is now populated.
