### ISSUE TITLE
Allow users to manage their feeds in /feeds

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#57]
Things we should have:

- Drop a feed (_that is the ownership/management of it_)
- Adjust the description/tagline of the feed

__NOTE:__ Dropping a feed should **NEVER** delete the feed on the backend itself, just the User<->Feed ownership of.

We _might_ want to consider "Transferring" feeds from one user to another at some point, but that's out-of-scope here IHMO.

**Comment by dooven** [comment]
Im thinking we add a button, to manage a feed that a user owns. If they click on it they'll get pushed to a new page say `/user/<feed_name>/manage` where they can manage the feed there.

**Comment by prologic** [comment]
Nice I love it! 😍

**Comment by prologic** [comment]
This should also include being able to upload a custom Avatar for a User's feed too btw 👍

**Comment by prologic** [comment]
> This should also include being able to upload a custom Avatar for a User's feed too btw 👍

Maybe as a separate PR 👍

**Comment by dooven** [comment]
> > This should also include being able to upload a custom Avatar for a User's feed too btw +1
> 
> Maybe as a separate PR

Sounds good. I'll make another PR for the images :+1:

**Comment by dooven** [comment]
For the avatars, do also want it so that the it'll get fetched from `/user/:feedName/avatar.png`?

Or do we want to add a AvatarURL field in the Feed struct. That way, everytime we upload a new image, it'll have different names, which will avoid caching issues.

**Comment by dooven** [comment]
Re-opening this issue. :grimacing:  Sorry i kept on closing them coz i linked it on the PR above.

**Comment by prologic** [comment]
> Re-opening this issue. 😬 Sorry i kept on closing them coz i linked it on the PR above.

Its my fault :D I _should_ just make smaller Issues that can only be done with a single PR :P

**Comment by dooven** [comment]
@prologic thoughts on this [comment](https://github.com/prologic/twtxt/issues/57#issuecomment-668234699)?

**Comment by prologic** [comment]
> For the avatars, do also want it so that the it'll get fetched from `/user/:feedName/avatar.png`?
> 
> Or do we want to add a AvatarURL field in the Feed struct. That way, everytime we upload a new image, it'll have different names, which will avoid caching issues.

Let's do the later? Also I was thinking about the recent new media upload feature too; so maybe let's think about converging down this path....

Right now when a user upload some media, they get a unique URI for that media (_with some background processing to downscale it, etc. its not perfect yet but its a start_); But  it get shoved into `config.Data` + `mediaDir`. This means that the associated of User <-> Media is not preserved. As in if a user decides to migrate/move their Twtxt feed/account to say another Twtxt Pod or just simply take their data with them and delete/archive their account it is impossible to give them their "Uploaded Media" too  (_right now_).

So I'm thinking of the following structure:

- `./data/<user||feed>/` one per user/feed (_they're really the same thing, just treated subtly differently_)
  - `avatar.png` -- User/Feed avatar (_maybe let's just fix user avatars too and just use a uuid?_)
  - `twtxt.txt` -- The User/Feed's actual Twtxt.txt feed itself (_same as what's in `./data/feeds/*`)
  - `./media/*.png` -- Any user uploaded media content.

What do you thinnk?

I _think_ the existing URI structures are fine, just some of the backend needs to be updated/tweaked a bit and its a bit late now for existing media; but that's okay.

**Comment by dooven** [comment]
I like the directory structure yea since this will make it easier for users to migrate from one Pod to another. 

Going back to the topic of moving the AvatarURL to the feed/user struct, how do we handle displaying those avatars for external Pod? Right now we have it so it will always be `/user/<name>/avatar.png`. But if we decide to use UUIDs and use for the avatar URL, it might complicate getting those URLs from  other Pods.

**Comment by prologic** [comment]
> Going back to the topic of moving the AvatarURL to the feed/user struct, how do we handle displaying those avatars for external Pod? Right now we have it so it will always be /user/<name>/avatar.png. But if we decide to use UUIDs and use for the avatar URL, it might complicate getting those URLs from other Pods.

Yes its for this reason I _think_ we just put up with Cloudflare questionable behavior? And just go with:

- /user/:user/{twtxt.txt,avatar.png}
- /feed/:feed/{twtxt.txt,avatar.png}

We can `301 Moved Premaritally` the old feed URIs easily. What do you think? Let's optimise for whats going to be easier for Pod<->Pod interactions and even potentially fetching/displaying external feed avatars (_if one if found alongside their `twtxt.txt`_). Sound okay?

**Comment by dooven** [comment]
I think for now,  can use the old directory structure. I added a PR to add the feed avatar here https://github.com/prologic/twtxt/pull/93

Then maybe we can split the work for restructuring the user/feed data on another issue

**Comment by prologic** [comment]
> Then maybe we can split the work for restructuring the user/feed data on another issue

I like this kind of thinking! Move fast™

**Comment by prologic** [comment]
@dooven This is done right? Are we missing anything now?

**Comment by dooven** [comment]
Oh yeah. We can close this now
