### ISSUE TITLE
Can't update my avatar

### ISSUE THREAD

**Issue by lwojcik** [prologic/twtxt#63]
As title says I guess.

I'm trying to use [the same image as on GitHub](https://avatars3.githubusercontent.com/u/1711174?s=400&u=17b218dca297ad6d0f264cbf91098f97b658c661&v=4) and I get 'Successfully updated' message, but the avatar won't change.

Tried rescaling it down to 60x60 and converting to PNG but no luck so far.

EDIT: Additionally, when I try to update my settings while leaving the avatar field empty, I get an error 'http: no such file'.

**Comment by prologic** [comment]
@lwojcik I _think_ you did manage to succeed finally? I noticed someone/something managed to crash the backend, so I fixed that rather quickly.

Let me see if I can repro the 2nd part you reported.

**Comment by lwojcik** [comment]
The avatar sorted itself out magically while I was waiting for your reply. :)

The 2nd part seems to be fine now as well.

**Comment by prologic** [comment]
Awesome :)
