### ISSUE TITLE
APIv1 for CLI, Mobile and Integrations

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#65]
We need an APIv1 to start building out APIs developers can write interesting clients and integrations against a hosted [twtxt.net](https://twtxt.net) instance (_hopefully a network of them_).

API Spec can be found (_WIP_) at: https://hackmd.io/yqll3RMRSTmMSMg7OoP2dQ

I will begin work today on a prototype APIv1 that will at least perform these basic functions:

- `/auth` endpoint that accept a Username and Password and produces a JWT token for the client to use to authenticate future sessions with the API.
- `/timeline` endpoint to fetch a copy of the feed cache for the authenticated user associated with a signed JWT token.
- `/post` endpoint to create a new Twt post on behalf of a user associated with the signed JWT token

This is all I will attempt to build for today, let's see how this goes. This _more or less_ matches what we discussed above in the API Spec so far; details may of course change as we continue to flesh this out.

This is a hard requirement for #24

**Comment by lwojcik** [comment]
I can write and maintain wrapper library in JS / Node once spec gets finalized.

**Comment by prologic** [comment]
> I can write and maintain wrapper library in JS / Node once spec gets finalized.

That would be good :) I can see us going down a ReactJS client (_even though I wanted to avoid "heavy" use of client-side JS/CSS 🤣_) -- But OTOH a "very light" JS library that talks to the API that's coming is good I think if we can do two things for the Web:

- Be as fast/light as possible
- Degrade gracefully

**Comment by lwojcik** [comment]
Reusable React components is something I can offer later once the library reaches the point of being usable.
