### ISSUE TITLE
Custom CSS/JS needs cache busting

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#70]
ssa 👍 

As we add more UI/UX facing features (_that degrade nicely_); this is becoming more and more important. 

Its both a bug and an enhancement :)

**Comment by dooven** [comment]
Im thinking of adding the commit hash to the static content's path for example:  `/css/3d9d1c5346b1b0b16b823c69fe1e7c64b3466aab/pico.css`. I created a [branch here](https://github.com/prologic/twtxt/compare/master...dooven:cache-bust-test). lmk what you think!

**Comment by prologic** [comment]
Yes please! This is the _usual_ way of handling this :)
