### ISSUE TITLE
Update README with a better Demo (gif)

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#72]
Hey @dooven Would you be able to do this? I _really love_ your GIF(s) you've done for your "Test Plan"(s). I think it would add a nice touch for anyone coming across this project on Github.

What do you think? Those static screenshots are the best I can do and they kind of suck :)

**Comment by dooven** [comment]
For sure! I'll get some gifs tomorrow!

**Comment by dooven** [comment]
What do you think about this one? I kept it short because of GitHub's file size limit

It shows the following: 
1. Creating a tweet
2. User profile page
3. Feeds
![out](https://user-images.githubusercontent.com/15314237/89128900-1c2bf280-d4b6-11ea-9471-ba1cc917bb5d.gif)

**Comment by prologic** [comment]
Looks great 👍 Hmmm I just saw that horrible bug where the UI flashes between Dark and Light themes 🤔

**Comment by dooven** [comment]
Oh right :thinking: I'll just use Dark Theme for this gif so that that bug wont be visible. Then maybe we can create a new issue to deal with the bug you just described.

**Comment by dooven** [comment]
Got this new one
![file](https://user-images.githubusercontent.com/15314237/89133451-30cdb200-d4d9-11ea-8a11-aab67c6fac6a.gif)

**Comment by prologic** [comment]
Even better 🤗

**Comment by prologic** [comment]
This is done.
