### ISSUE TITLE
Filter by feed

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#77]
As a user it would be nice if I could filter my own personal [Timeline[(https://twtxt.net) by the Feed I'm interested in particular at that moment. I want to be able to (_sometimes_) just see a single feed at a time, especially when I follow a lot of feeds and my timeline gets cluttered up.

**Comment by dooven** [comment]
Im thinking of adding a [Hide in timeline] button for the feed/users that i dont want to show up in my timeline. This can be configured in the settings page. What do you think?
![screenshot_35](https://user-images.githubusercontent.com/15314237/89721172-8271b300-d997-11ea-9576-52eda7c82365.png)

**Comment by prologic** [comment]
> Im thinking of adding a [Hide in timeline] button for the feed/users that i dont want to show up in my timeline. This can be configured in the settings page. What do you think?

My only "issue" with this is that it doesn't sort of mean anything. If you "Hide from timeline" a feed, you may as well "Unfollow" it. Right?

OTOH; the OP in this issue talks about "filtering by feed" -- Think of this like a "show me all twts by this user" (_which we have_) but if you use [twtxt.net](https://twtxt.net) like I do where I use it both as a news reader and social network, sometimes its helpful to just "narrow down" / "drill down" to one particular source feed.

Does this make sense? I'm not so sure on the "Hide from timeline" idea though... What do think?

**Comment by prologic** [comment]
Also was just thinking about this some more at the shops... Another way to "fix this" problem; which is really just a UI/UX problem as far as I'm concerned is to treat external feeds the same as internal ones.

Right now if you say click on an external feed you're following (_regardless of where it comes from_) it just show shows you a `text/plain` view of it. No reason we can't treat this the same as internal users/feeds right?

That way things "just work"™ and we get the capability of "filtering by feed" for free 👍

**Comment by dooven** [comment]
Like if we click on the external feed it should act like a like what an internal feed does (it will show all the post for that feed in the feed's profile)?

**Comment by prologic** [comment]
Yes! Why not 👍 

Also the new @mention type-ahead could benefit from this too as I notice that avatars for things that are in fact external feeds report a 404 for their avatar (_obviously_).

I _think_ yes we should consolidate that UI/UX and behaviour and just treat all feeds the same regardless of whether they are internal or external. At the same time we should teach the cache how to look for a remote `avatar.png` to download and cache for the purposes of displaying an avatar for an external feed (_for instance it would be from another twtxt pod_)

**Comment by prologic** [comment]
For now... Let's create a MVP PR that moves in this direction that archives what we want our of this issue? (_small iterative steps_)

**Comment by prologic** [comment]
@dooven I _think_ we have this now? Can we close it? Sure we can extend/improve this to "mentions" of external feeds, fetching an avatar for them (_if we can find one_) and pre-fetching if we don't have the mentioned feed in our cache (_but these can all be separate issues/PRS_).

**Comment by dooven** [comment]
Yeah sounds good. We can do those improvements on another pr
