### ISSUE TITLE
Search by #tag

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#78]
As. a user it would be awesome if I could take advantage of the (_by convention_) `#hashtag`(s) that users are used to using to tag their Twt(s). If I could click on / follow a tag (_automatically linked_) and my Timeline was then filtered by all Twts that match that tag this would help me find more meaningful discussions with similar tags.

**Comment by dooven** [comment]
Im going to start working on this soon (probably tomorrow). Just like the mentions (@<user>), tweets that matches the hashtag regex will get expanded e.g. `#testing` -> `[testing](https://twtxt.net/search?hashtag=testing)`.

**Comment by dooven** [comment]
@prologic Just wondering if you can explain how tweet text like
```
@<hallo http://0.0.0.0:8000/user/hallo/twtxt.txt> from @<testing http://0.0.0.0:8000/user/testing/twtxt.txt>
```

Gets transformed into an html 
```
<a href="http://0.0.0.0:8000/user/hallo/twtxt.txt">hallo</a>
```

I noticed in the `utils.go` file you have this function 
```go
		renderHookProcessURLs := func(w io.Writer, node ast.Node, entering bool) (ast.WalkStatus, bool) {
			span, ok := node.(*ast.HTMLSpan)
			if !ok {
				return ast.GoToNext, false
			}

			leaf := span.Leaf
			doc, err := goquery.NewDocumentFromReader(bytes.NewReader(leaf.Literal))
			if err != nil {
				log.WithError(err).Warn("error parsing HTMLSpan")
				return ast.GoToNext, false
			}

			a := doc.Find("a")
			href, ok := a.Attr("href")
			if !ok {
				return ast.GoToNext, false
			}

			if isLocal(href) {
				href = UserURL(href)
			} else {
				return ast.GoToNext, false
			}

			html := fmt.Sprintf(`<a href="%s">`, href)

			io.WriteString(w, html)

			return ast.GoToNext, true
		}
```

My question is is this `<hallo http://0.0.0.0:8000/user/hallo/twtxt.txt>` an HTMLSpan?

**Comment by dooven** [comment]
Oh :facepalm: just noticed `FormatMentions` utlity function :sweat_smile:

**Comment by prologic** [comment]
> My question is is this <hallo http://0.0.0.0:8000/user/hallo/twtxt.txt> an HTMLSpan? Im just confused because was searching for this syntax in markdown, and all I find is "Autolinks".

No its part of the [twtxt](https://twtxt.readthedocs.org) spec 👍

**Comment by prologic** [comment]
This is how you tag someone in a twtxt twt :)
