### ISSUE TITLE
Twt deletion

### ISSUE THREAD

**Issue by lwojcik** [prologic/twtxt#85]
I think it would be nice to be able to [correct mistakes](https://twtxt.net/user/lukem#7c7sz6cxst7jrelw5brfhjt25mrsffypbzsh7y42z2worivcgfca) in latest twt, at least for a limited time, either with an 'Edit' button or by deleting the twt and posting it again. Sausage fingers and poorly calibrated autocorrections would be happier. :)

**Comment by prologic** [comment]
I agree! As a user myself of the platform I've fat-fingered a few myself; as I own/operate this particular Pod ([twtxt.net](https://twtx.net)) it was _trivial_ for me to just go fix my feed by hand. But I _don't_ really want to have to keep doing that nor do I expect non-technical minded folks that _we want_ to enjoy the same benefits as we do to be expected to do this or even know how.

So yes great idea; but limited to just the last Twt/line? So we preserve the [twtxt](https://twtxt.readthedocs.org) as much as possible. I _think_ being able to "word smifth" the last line or nuke it is "okay" IHMO; but beyond that you start to enter "breaking" territory.

**Comment by prologic** [comment]
i;e: [twtxt.net](https://twtxt.net)'s backend treats the `twtxt.txt` file spec as a "Write-Ahead-Log" / WAL in technical terms.

**Comment by lwojcik** [comment]
Yeah, being able to fix last line is more than enough IMO. If I start writing a new twt I probably don't care about older ones anyway.
