### ISSUE TITLE
Permit Editing/Deletion of last Twt within a configurable Max Undo Time

### ISSUE THREAD

**Issue by prologic** [prologic/twtxt#89]
For this to be implemented it must:

- [ ] Add options to `./cmd/twtd/main.go`, `./internal/options.go` and `./internal/config.go`
- [ ] Restrict the display of the `[Edit]` and `[Delete]` actions if the amount of time past has exceed the configured pod's `--max-undo-time`
- [ ] Ensure that the backend also respect the configured `--max-undo-time` and refuses forged requests that violate the pod's configuration.

**Comment by lwojcik** [comment]
Is it absolutely necessary to lock twt deletion behind a time constraint?

Editing I can understand and I'm okay with that. I'm also okay with the fact I can delete only my latest twt.

However, I'm just a human being and I may sometimes post things I'll regret later. Knowing that it's a one-way alley I may spend more time self-censoring than actually posting things. I know people on Twitter who treat it like stories on Snapchat, e.g. doing regular purges and keeping their tweet count low for their own reasons.

Maybe setting separate flags like `--max-undo-time` and `--max-edit-time` for respective actions could be a viable solution.

**Comment by prologic** [comment]
Yeah I'm on the fence with this one. Mostly my thinking was at first "oh wait anyone can just keep going back in time and just edit/delete every line". 🤷‍♂️

I like your idea though:

> Maybe setting separate flags like --max-undo-time and --max-edit-time for respective actions could be a viable solution, so that I could limit editing and allow for unlimited deletions.

Seemsreasonablee to provide two different config options for a pod owner/operator.

**Comment by prologic** [comment]
I _think_ we don't do this. If any user of the [twtxt.net](https://twtxt.net) software/platform wants to go and delete their entire feed, they're welcome to do so. But its really designed only to "edit/delete" the last twt :D
