### ISSUE TITLE
IndieWeb support

### ISSUE THREAD

**Issue by fluffy-critter** [prologic/twtxt#91]
Hi, I just found out about this project, and it looks like it would do well with some sort of [IndieWeb](https://indieweb.org/) integration.

Briefly, IndieWeb is a set of ideals and protocols that websites can use to follow each other and send each other reples — sound familiar? :) 

The specific things that I'd recommend implementing:

* [h-feed/h-entry/h-card](https://indieweb.org/microformats2) — microformats that are used to provide semantic/sharing information (authorship, post text, etc.); publishing this is as simple as decorating DOM elements with a handful of CSS classes, and receiving it is straightforward with a number of existing parser libraries (including https://github.com/willnorris/microformats for golang)
* [Webmention](https://indieweb.org/webmention) — a mechanism for sending and receiving replies/likes/bookmarks/RSVPs/etc. (which is built on top of the microformats, h-entry and h-card in particular)
* [WebSub](https://indieweb.org/WebSub) — push notifications for subscription updates (useful for RSS/atom readers as well)

Also it isn't clear to me as to whether you have support for RSS/Atom feeds, but if not, it'd be helpful to provide Atom so that other things can interoperate as well. Atom even has support for push (via WebSub) and boosting/reposting content!

Anyway, welcome to the decentralized web neighborhood. I hope to see more from this project. :)

**Comment by fluffy-critter** [comment]
Oh, also, if you do decide to go this route I'd highly recommend making user profile pages at least partially public rather than redirecting to a login page, so that they can serve up an h-card and h-feed to IndieWeb-enabled readers.

**Comment by prologic** [comment]
I can't reply properly now -- Heading out to play 🏓 However I wanted to mention a few things:

- We are actively exploring ways we _could_ interoperate with ActivityPub, MicroPub and some of the IndieWeb protocols/microformats.
  - It isn't yet clear ot me which ones we'll adopt and which will be suitable, etc.
- RSS/Atom is actually already builtin with a dedicated external service called [rss2twtxt](https://github.com/prologic/rss2twtxt) which runs are [feeds.twtxt.net](https://feeds.twtxt.net) and used as a "feed source" along with [we-are-twtxt](https://github.com/mdom/we-are-twtxt) which feeds.twtxt.net exposes.
  - So we have RSS/Atom; just not in the direction you're expecting :)

**Comment by fluffy-critter** [comment]
Ah, it's refreshing to see support for subscribing to external RSS feeds! That's pretty uncommon in systems like these. For good interoperability you should probably expose feeds in both directions though, or at least provide some mechanism for someone to subscribe that way even if it's through a translator service.

Incidentally, if you support h-feed, then people could use Granary.io to subscribe via RSS/Atom. It wouldn't have WebSub support though.

**Comment by prologic** [comment]
So I added support last night for `-O/--open-profiles` so an operator of a Twt pod can choose to have open profiles.  I haven't decided to open them up yet on https://twtxt.net/ but I _may_ do so.

Alao I spent considerable time late through the night playing around with a Managed Hosted Mastodon instance (_I bought one_), and getting to know what Mastodon is like. There is a rather long discussion of it over at #86 

In terms of the OP here however, I _feel_ like it would be possible to add some of the IndieWeb features you speak of to the software that backs twtxt.net (_this repo_); it might even make sense to add MicroPub support. But I'm a bit iffy about ActivityPub and the whole Fediverse thing after having played around a lot with Mastodon...

**Comment by fluffy-critter** [comment]
Yeah, ActivityPub/Fediverse are a gigantic can of worms to support. Fortunately IndieWeb protocols are way more decoupled and a lot easier to incrementally support. Which is why I'm focusing on IndieWeb support in [my own stuff](https://plaidweb.site), as well; I want to support ActivityPub someday but it's an *extremely* low priority.

**Comment by prologic** [comment]
@fluffy-critter Would you be willing/interested in helping the project out here and contributing? I _did_ think at once stage that adding IndieAuth support (#11) would be useful, but as I clearly don't know enough about IndieWeb protocols/conventions (_yet_); I need help! I would love to see what adding IndieAuth, *card support would look like.

I can easily add twtxt -> RSS/Atom (_the other way around from what https://feeds.twtxt.net/ provides_); but I worry about the risk of "infinite recursion" between twtxt -> RSS/Atom -> twtxt (_it could be abused_).

**Comment by fluffy-critter** [comment]
I already have a lot on my plate but I'd certainly consider it, sure. :)

Why would there be a recursion issue? If someone subscribes to another twtxt user via RSS instead of via twtxt, what would that cause other than there being an "alternate universe" view of the posts with possibly worse formatting?

If you do decide to add a public non-twtxt feed I'd highly recommend using Atom so that you can use the `<source>` element for boosts/shares.

**Comment by prologic** [comment]
> Why would there be a recursion issue? If someone subscribes to another twtxt user via RSS instead of via twtxt, what would that cause other than there being an "alternate universe" view of the posts with possibly worse formatting?

Consider the following:

- User A on twtxt.net goes and creates a feed of their twtxt feed over at https://feeds.twtxt.net/
- User A then follows this feed.
- User A makes a Twt.
- User A's timeline is now populated with their new Twt
- On the next feed fetch, it is also populated with that same Twt from their RSS/Atom feed of thwit twtxt feed

Mayne there is no way to cause an infinite recursion as such, nbut this is what I was thinking  :)

**Comment by fluffy-critter** [comment]
That doesn't seem like a critical error that needs to be avoided at all expenses, to me. It's just someone who really likes seeing themself talk. :)

**Comment by prologic** [comment]
Okay yeah I agree!

Alright. I'll write up an issue to add RSS/Atom support as an output of a user's Twtxt feed.

Can you help me understand why it _should_ be Atom and not RSS or both? Thanks :D

**Comment by fluffy-critter** [comment]
There is no reason to support plain old RSS, because Atom is a strict superset of it, and Atom in particular provides various extensions, as well as native sharing of items via `<source>`. It also has support for backfilling old content, in case that's a thing you want to allow for a distributed social situation, and there's an extension to support deleting items as well (while with RSS once something picks it up from a feed it's going to be there forever).

Any feed reader that supports RSS will also support Atom, so there's no particular reason to support both.

**Comment by prologic** [comment]
Cool I'll have a look around for a good Gp library for this. Thanks! => #94

**Comment by prologic** [comment]
@fluffy-critter I was playing around with WebMentions last night (_all night! 🧐_) in [this branch](https://github.com/prologic/twtxt/tree/webmentions) and using this [forked library](https://github.com/prologic/webmention)...

It's not quite finished yet, but I _think_ I've worked out enough of how it works that this might get merged soon once I tidy it all up.

Do you mind taking a look and give me some feedback? As we grow the no. of pods in the network (_today we have three_) it's going to become more important that we have ways to discover other pods and users in the network and interact across them.

One of the original ideas we had around this was:

> If User A on Pod X follows user B on pod Y, User B gets "notified".

Same idea for mentioning.

Thoughts? RIght now I have it setup such that there is a `/webmention` endpoint at the root of the pod's Base URL and that when you mention someone on another pod the source URI is the `/twt/:hash` of the source post. What I haven't gotten working yet is to (_from the backend_) validate the source URI in some way and work out who they are in terms of their "Nickname" (_if an external `twtxt.txt` feed_) or their "Username" (_if a user from another pod_).

**Comment by fluffy-critter** [comment]
I don't know if there's any codified mechanism for sending a follow mention, although I would assume that having your following list (on your profile) present all of the folks you're following with something like `<a href="https://instance.example/user/foo" class="u-follow-of">` or the like, that should be enough to satisfy the relationship link. This would be a good question to ask on Indieweb chat, but from https://indieweb.org/follow it seems that `u-follow-of` is what people have standardized on for a follow-type mention.

As far as verifying the incoming mention, that should be pretty straightforward; generally you just retrieve the URL that was sent as the mention source, then verify that the target URL is indeed linked to from that URL, and optionally parse the mf2 on the page to get metadata about the sent mention (like what sort of mention it is, and the identity of the sender and whatever the canonical URL for the mention itself should be). I've not written that logic myself (I just use webmention.io for my incoming mentions) and that can be a bit fiddly.

Out of curiosity, why are you declaring a webmention endpoint on the timeline? On pages where there's no sense in processing an incoming mention I don't think there's a particularly good reason to declare a webmention endpoint; where would that mention go to? I'd expect incoming mentions to go either to a user profile or to a specific tweet, and I don't think anything else really makes much sense, unless you want to gather mentions to the instance itself.

**Comment by prologic** [comment]
I spun up two pods with this branch (_now cleaned up a lot_):

- https://twtxt-webmentions1.mills.io/
- https://twtxt-webmentions2.mills.io/

**Comment by prologic** [comment]
It still has a few quirks, like the incoming webmention and source URI. Still haven't quite figured out how to properly identify the mention by "nickname"/"username".

**Comment by prologic** [comment]
> Out of curiosity, why are you declaring a webmention endpoint on the timeline? On pages where there's no sense in processing an incoming mention I don't think there's a particularly good reason to declare a webmention endpoint; where would that mention go to? I'd expect incoming mentions to go either to a user profile or to a specific tweet, and I don't think anything else really makes much sense, unless you want to gather mentions to the instance itself.

Thanks! This is precisely the kind of feedback I needed! I'm not even sure how how to process these incoming webmentions just yet even from another twtxt.net pod (_let alone a webmention in general_). I had a lot of problems with the mf2 parsing code in the library I was using so I ripped it all out (_get the basics working first_).

**Comment by fluffy-critter** [comment]
So, my suggestion would be that since you know which user and/or post a URL maps to, there isn't really any reason to encode the user into the endpoint identifier; you can just parse the target URL and see that it maps to e.g. https://twtxt.net/user/prologic and that's a generic notification to be sent to you, or if it maps to https://twtxt.net/twt/lxpuuzo3g7hjje2f6vdcsw5fvgettwv75fxcwzbtt5fhfluakgtq then it should be a reply to that specific post.

Parsing out the mf2 for metadata display purposes is optional, but highly recommended. You can use pin13.net as a reference for how it should be parsed.

So for example if you got an incoming webmention from (just for an example, this doesn't actually link to a post on twtxt) http://beesbuzz.biz/blog/6265-Two-PSAs-regarding-IndieAuth then from pin13.net you can see that there's an h-entry with a title (`p-name`) of "Two PSAs regarding IndieAuth" and an h-card that declares the author as "fluffy" with related metadata like my homepage, avatar image, and a few other things.

Basically `h-entry` refers to the entry, and `h-card` refers to the author of the entry. If there are multiple `h-entry` records on a page, you should use the one which contains the mention URL; for example http://pin13.net/mf2/?url=http%3A%2F%2Fbeesbuzz.biz%2Fblog%2Fchatter%2F8062-Re-Clientwide-Webmentions shows you the mf2 for a reply from my site to someone else's blog entry, or http://pin13.net/mf2/?url=http%3A%2F%2Fbeesbuzz.biz%2Fblog%2Fchatter%2F is a page with a whole bunch of entries, some of which are replies. (Note that I only personally send mentions from the individual entry URL but that isn't guaranteed.)

Also the `u-url` property might not be the same as the actual source URL of the mention; you should record them both, and probably indicate if they're different somehow. A lot of webmention services like brid.gy will generate synthetic pages that link to the target, but then declare a u-url of the original page, which is better to display, but that can lead to potential spoofing stuff, thus wanting to make it possible to see if the source URL is different than the declared u-url URL.

In any case I highly recommend joining in on indieweb chat and asking folks there for their opinions. I'm just one person who does this stuff and I'm far from an authority on things (I'm always discovering I got some weird detail wrong, for example).

**Comment by prologic** [comment]
The problem I've found myself now in is one of the "right flows". I'm not sure I'm getting these quite right to be honest for the use-case at hand -- which is basically a web interface / hosted platform around twtxt.txt feeds.

**Comment by prologic** [comment]
Btw ... as a side-effect of the webmentions branch it will also include `h-entry` and `h-card` formats.
