### ISSUE TITLE
Create "Following" page

### ISSUE THREAD

**Issue by dooven** [prologic/twtxt#97]
**Is your feature request related to a problem? Please describe.**
- This issue adds the "Follower" page https://github.com/prologic/twtxt/issues/35#issuecomment-664735822

**Describe the solution you'd like**
- As a user I want to be able to click on the "Following" link which will take me to all the user/feed that im following
![screenshot_34](https://user-images.githubusercontent.com/15314237/89699422-09fdea00-d8e4-11ea-83f1-d71017f38786.png)

**Additional context**
- You can use this [PR](https://github.com/prologic/twtxt/pull/45) as a reference when building this feature

**Comment by prologic** [comment]
Done in 34a0f97
