### ISSUE TITLE
API endpoint /timeline retrieving wrong timestamp

### ISSUE THREAD

**Issue by aaadonai** [prologic/twtxt#99]
**Describe the bug**
Looks like the API is returning wrong timestamp (Created field) for the first twt in the list. It seems it is always 7 minutes faster from the time I posted. See JSON response below. Is this happening because the server time is wrong? This can be an issue for clients that will base their calculation to display the X minutes ago from the localtime minus the time of the post on the created field. Perhaps API could send server_time also in UTC so the client would use that to make its calculations.

Sample JSON:
```
{
	"twts": [{
		"Twter": {
			"Nick": "antonio",
			"URL": "https://twtxt.net/user/antonio/twtxt.txt"
		},
		"Text": "That is definitely something weird with the API and timestamps/",
		"Created": "2020-08-08T06:58:22Z"
	}, {
		"Twter": {
			"Nick": "antonio",
			"URL": "https://twtxt.net/user/antonio/twtxt.txt"
		},
		"Text": "Looks like the posts when retrieved via /timeline API endpoint are showing 7 minutes faster.",
		"Created": "2020-08-08T06:54:52Z"
	}
```

curl example: (replace with your token)
```
curl --location --request POST 'https://twtxt.net/api/v1/timeline' \
--header 'token: <your token here>' \
--data-raw '{
    
}'
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to website a make a post
2. Use the curl above to retrieve the post via the API
3. Make a second post
4. Retrieve one more time via curl
4. Observe JSON responses for both cases.

**Expected behavior**
Created field should reflect the time of the post.

**Comment by prologic** [comment]
Yeah it _may_ be time skew on the server infra. Let me check and report back...

**Comment by prologic** [comment]
Confirmed:

```console
# ntpd -w -p pool.ntp.org
ntpd: reply from 27.124.125.252: offset:-490.386446 delay:0.071073 status:0x24 strat:4 refid:0x7bc89fa2 rootdelay:0.002304 reach:0x01
```

**Comment by prologic** [comment]
Fixed! (_permanately_):

```console
# ntpd -w -p pool.ntp.org
ntpd: reply from 139.99.236.185: offset:-0.004208 delay:0.017349 status:0x24 strat:4 refid:0x7bc89fa2 rootdelay:0.009659 reach:0x01
ntpd: reply from 139.99.236.185: offset:-0.004015 delay:0.017444 status:0x24 strat:4 refid:0x7bc89fa2 rootdelay:0.009659 reach:0x03
```

**Comment by prologic** [comment]
Please confirm 🤗

**Comment by aaadonai** [comment]
Yes. Thank you. It is fixed. Closing this issue.
